name: CI build

on:
  push:
    branches:
      - master

jobs:
  build:

    env:
      PY_COLORS: "1"
      GLOBAL_PROXY: ${{ secrets.GLOBAL_PROXY }}
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1    
    - name: test
      run: python test.py
